### ISSUE TITLE
Pretty cool stuff

### ISSUE THREAD

**Issue by sparrowDom** [lucbu/slack-jukebox#3]
can you please in package.json update the `ytdl-core` from: 
```
"ytdl-core": "^0.20.1"
```
to 
```
"ytdl-core": "^1.0.3"
```
This change prevents the app from crashing on specific Youtube Urls

**Comment by lucbu** [comment]
I updated all the dependencies to the latest versions

**Comment by sparrowDom** [comment]
that was fast thanks! 👍
